site_name: Vendor API Docs - Sastodeal
nav:
    - Introduction: index.md
    - API Documentation:
      - Authentication API: api/authentication.md
      - SKU List API: api/sku/list.md
    - Contact Us: contact-us.md
theme:
  name: material
  palette:
    primary: teal
  logo: ''
copyright: 'Copyright &copy; 2021 Sasto Deal Pvt. Ltd'