site_name: Vendor API Docs - Sastodeal
nav:
    - Introduction: index.md
    - API Documentation:
      - Vendor Integration API: api/vendor-integration-api.md
    - Contact Us: contact-us.md
theme:
  name: material
  palette:
    primary: teal
  logo: ''
copyright: 'Copyright &copy; 2021 Sasto Deal Pvt. Ltd'
